<a href="https://colab.research.google.com/github/sanskarshah827/SANSKAR-AI/blob/main/Worksheet3_sanskar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import seaborn as sns

1. Sorting and Subsetting:
Complete all following Task:
• Dataset for the Task: "titanic.csv"
Following task is common for all the problem:
1. Load the provided dataset and import in pandas DataFrame.

In [5]:
data = pd.read_csv("/content/drive/MyDrive/saskar ai/Titanic-Dataset.csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
df = pd.DataFrame(data)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [8]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Problem 1 - Sorting:
1. Create a DataFrame called fare that contains only the Fare column of the Titanic dataset. Print the
head of the result.

In [9]:
fare = titanic[['fare']]
fare.head()

      fare
0   7.2500
1  71.2833
2   7.9250
3  53.1000
4   8.0500

2. Create a DataFrame called class age that contains only the Pclass and Age columns of the Titanic
dataset, in that order. Print the head of the result.

In [10]:
class_age = titanic[['pclass', 'age']]
class_age.head()

   pclass   age
0       3  22.0
1       1  38.0
2       3  26.0
3       1  35.0
4       3  35.0

3. Create a DataFrame called survived gender that contains the Survived and Sex columns of the
Titanic dataset, in that order.Print the head of the result.

In [11]:
survived_gender = titanic[['survived', 'sex']]
survived_gender.head()

   survived     sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

Problem - 2 - Subsetting:
Complete all the following Task:
Subsetting Rows:
1. Filter the Titanic dataset for cases where the passenger’s fare is greater than 100, assigning it
to fare gt 100.View the printed result.

In [12]:
fare = titanic[titanic['fare']> 100]
fare

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
27,0,1,male,19.00,3,2,263.0000,S,First,man,True,C,Southampton,no,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
88,1,1,female,23.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
118,0,1,male,24.00,0,1,247.5208,C,First,man,True,B,Cherbourg,no,False
195,1,1,female,58.00,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
215,1,1,female,31.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
258,1,1,female,35.00,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
268,1,1,female,58.00,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
269,1,1,female,35.00,0,0,135.6333,S,First,woman,False,C,Southampton,yes,True
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
299,1,1,female,50.00,0,1,247.5208,C,First,woman,False,B,Cherbourg,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
306,1,1,female,NaN,0,0,110.8833,C,First,woman,False,NaN,Cherbourg,yes,True
307,1,1,female,17.00,1,0,108.9000,C,First,woman,False,C,Cherbourg,yes,False
311,1,1,female,18.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
318,1,1,female,31.00,0,2,164.8667,S,First,woman,False,C,Southampton,yes,False
319,1,1,female,40.00,1,1,134.5000,C,First,woman,False,E,Cherbourg,yes,False
325,1,1,female,36.00,0,0,135.6333,C,First,woman,False,C,Cherbourg,yes,True
332,0,1,male,38.00,0,1,153.4625,S,First,man,True,C,Southampton,no,False
334,1,1,female,NaN,1,0,133.6500,S,First,woman,False,NaN,Southampton,yes,False
337,1,1,female,41.00,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
341,1,1,female,24.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
373,0,1,male,22.00,0,0,135.6333,C,First,man,True,NaN,Cherbourg,no,True
377,0,1,male,27.00,0,2,211.5000,C,First,man,True,C,Cherbourg,no,False
380,1,1,female,42.00,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True
390,1,1,male,36.00,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
393,1,1,female,23.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
438,0,1,male,64.00,1,4,263.0000,S,First,man,True,C,Southampton,no,False
498,0,1,female,25.00,1,2,151.5500,S,First,woman,False,C,Southampton,no,False
505,0,1,male,18.00,1,0,108.9000,C,First,man,True,C,Cherbourg,no,False
527,0,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,no,True
537,1,1,female,30.00,0,0,106.4250,C,First,woman,False,NaN,Cherbourg,yes,True
544,0,1,male,50.00,1,0,106.4250,C,First,man,True,C,Cherbourg,no,False
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
557,0,1,male,NaN,0,0,227.5250,C,First,man,True,NaN,Cherbourg,no,True
581,1,1,female,39.00,1,1,110.8833,C,First,woman,False,C,Cherbourg,yes,False
609,1,1,female,40.00,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
659,0,1,male,58.00,0,2,113.2750,C,First,man,True,D,Cherbourg,no,False
660,1,1,male,50.00,2,0,133.6500,S,First,man,True,NaN,Southampton,yes,False
679,1,1,male,36.00,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
689,1,1,female,15.00,0,1,211.3375,S,First,child,False,B,Southampton,yes,False
698,0,1,male,49.00,1,1,110.8833,C,First,man,True,C,Cherbourg,no,False
700,1,1,female,18.00,1,0,227.5250,C,First,woman,False,C,Cherbourg,yes,False
708,1,1,female,22.00,0,0,151.5500,S,First,woman,False,NaN,Southampton,yes,True
716,1,1,female,38.00,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True
730,1,1,female,29.00,0,0,211.3375,S,First,woman,False,B,Southampton,yes,True
737,1,1,male,35.00,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
742,1,1,female,21.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
763,1,1,female,36.00,1,2,120.0000,S,First,woman,False,B,Southampton,yes,False
779,1,1,female,43.00,0,1,211.3375,S,First,woman,False,B,Southampton,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
856,1,1,female,45.00,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False

2. Filter the Titanic dataset for cases where the passenger’s class (Pclass) is 1, assigning it to
first class.View the printed result.

In [13]:
first_class = titanic[titanic['pclass'] == 1]
first_class

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

3. Filter the Titanic dataset for cases where the passenger’s age is less than 18 and the passenger
is female (Sex is "female"), assigning it to female under 18. View the printed result.

In [14]:
female_un18 = titanic[(titanic['age']>18) & (titanic['sex'] == 'female')]
female_un18

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

Subsetting Rows by Categorical variables:
1. Filter the Titanic dataset for passengers whose Embarked port is either "C" (Cherbourg) or "S"
(Southampton), assigning the result to embarked c or s. View the printed result.

In [15]:
embarked_c_or_s = titanic[titanic['embarked'].isin(['C', 'S'])]
embarked_c_or_s

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

2. Filter the Titanic dataset for passengers whose Pclass is in the list [1, 2] (indicating first
or second class), assigning the result to first second class.View the printed result.

In [16]:
first_second_class = titanic[titanic['pclass'].isin([1, 2])]
first_second_class

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

3.2 Exploratory Data Analysis Practice Exercise - 1.


Answer the following questions from Dataset:
Which passenger had the highest fare paid relative to their age?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per year, containing the fare divided by the age of
the passenger(i.e., Fare/Age).

In [17]:
median_age = titanic['age'].median()
titanic['age'] = titanic['age'].fillna(median_age)

titanic['fare_per_year'] = titanic['fare'] / titanic['age']

titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_per_year
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.329545
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1.875876
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.304808
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1.517143
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.230000

2. Subset rows where fare per year is higher than 5, assigning this to high fare age.

In [18]:
high_fare_age = titanic[titanic['fare_per_year'] > 5]
high_fare_age

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_per_year
7,0,3,male,2.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False,10.537500
16,0,3,male,2.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False,14.562500
27,0,1,male,19.00,3,2,263.0000,S,First,man,True,C,Southampton,no,False,13.842105
31,1,1,female,28.00,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False,5.232886
43,1,2,female,3.00,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False,13.859733
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,0,3,female,6.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False,5.212500
824,0,3,male,2.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False,19.843750
827,1,2,male,1.00,0,2,37.0042,C,Second,child,False,NaN,Cherbourg,yes,False,37.004200
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False,22.590361
850,0,3,male,4.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False,7.818750

3. Sort high fare age by descending fare per year, assigning this to high fare age srt.

In [19]:
high_fare_age_srt = high_fare_age.sort_values(by='fare_per_year', ascending=False)
high_fare_age_srt

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_per_year
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False,164.728261
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False,75.775000
386,0,3,male,1.00,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False,46.900000
164,0,3,male,1.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False,39.687500
183,1,2,male,1.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False,39.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,1,3,male,3.00,1,1,15.9000,S,Third,child,False,NaN,Southampton,yes,False,5.300000
31,1,1,female,28.00,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False,5.232886
205,0,3,female,2.00,0,1,10.4625,S,Third,child,False,G,Southampton,no,False,5.231250
813,0,3,female,6.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False,5.212500
480,0,3,male,9.00,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False,5.211111

4. Select only the Name and fare per year columns of high fare age srt and save the result as result.
5. Look at the result.

In [20]:
result = high_fare_age_srt[['pclass', 'sex', 'age', 'fare_per_year']]
result
result.head(20)

     pclass     sex    age  fare_per_year
305       1    male   0.92     164.728261
297       1  female   2.00      75.775000
386       3    male   1.00      46.900000
164       3    male   1.00      39.687500
183       2    male   1.00      39.000000
827       2    male   1.00      37.004200
78        2    male   0.83      34.939759
644       3  female   0.75      25.677733
469       3  female   0.75      25.677733
831       2    male   0.83      22.590361
755       2    male   0.67      21.641791
788       3    male   1.00      20.575000
445       1    male   4.00      20.464575
803       3    male   0.42      20.277857
824       3    male   2.00      19.843750
381       3  female   1.00      15.741700
119       3  female   2.00      15.637500
737       1    male  35.00      14.637977
258       1  female  35.00      14.637977
311       1  female  18.00      14.576389

Which adult male passenger (age ≥ 18 and Sex is ’male’) paid the highest fare relative to their
class?
To answer the question perform following operations:
1. Add a column to the Titanic dataset, fare per class, containing the fare divided by the passenger
class i.e. Fare / Pclass.

In [21]:
titanic['fare_per_class'] = titanic['fare'] / titanic['pclass']
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_per_year,fare_per_class
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.329545,2.416667
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1.875876,71.283300
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.304808,2.641667
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1.517143,53.100000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.230000,2.683333

2. Subset rows where the passenger is male (Sex is ”male”) and an adult (Age is greater than or equal
to 18), assigning this to adult males.

In [22]:
adult_males = titanic[(titanic['sex'] == 'male') & (titanic['age'] >= 18)]
adult_males

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_per_year,fare_per_class
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.329545,2.416667
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.230000,2.683333
5,0,3,male,28.0,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True,0.302082,2.819433
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,0.960417,51.862500
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.402500,2.683333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True,0.375000,5.250000
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True,0.282000,2.350000
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,0.481481,6.500000
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1.153846,30.000000
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.242188,2.583333

3. Sort adult males by descending fare per class, assigning this to adult males srt.

In [23]:
adult_males_srt = adult_males.sort_values(by='fare_per_class', ascending=False)
adult_males_srt

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_per_year,fare_per_class
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True,14.637977,512.3292
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False,14.231367,512.3292
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False,13.842105,263.0000
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False,4.109375,263.0000
118,0,1,male,24.0,0,1,247.5208,C,First,man,True,B,Cherbourg,no,False,10.313367,247.5208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,0,3,male,36.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True,0.000000,0.0000
732,0,2,male,28.0,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True,0.000000,0.0000
822,0,1,male,38.0,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True,0.000000,0.0000
806,0,1,male,39.0,0,0,0.0000,S,First,man,True,A,Southampton,no,True,0.000000,0.0000
815,0,1,male,28.0,0,0,0.0000,S,First,man,True,B,Southampton,no,True,0.000000,0.0000

4. Select only the Name, Age, and fare per class columns of adult males sr and save the result
as result.
5. Look at the result.

In [24]:
result = adult_males_srt[['pclass', 'age', 'fare_per_class']]
result
result.head(20)

     pclass   age  fare_per_class
737       1  35.0        512.3292
679       1  36.0        512.3292
27        1  19.0        263.0000
438       1  64.0        263.0000
118       1  24.0        247.5208
557       1  28.0        227.5250
527       1  28.0        221.7792
377       1  27.0        211.5000
332       1  38.0        153.4625
373       1  22.0        135.6333
660       1  50.0        133.6500
390       1  36.0        120.0000
659       1  58.0        113.2750
698       1  49.0        110.8833
505       1  18.0        108.9000
544       1  50.0        106.4250
484       1  25.0         91.0792
245       1  44.0         90.0000
224       1  38.0         90.0000
453       1  49.0         89.1042

3.3 Exploratory Data Analysis with Group-by Method Practice Exercise:
Based on the dataset Answer the following question:
What percent of the total fare revenue came from each passenger class?
To answer the question perform following operation:
1. Calculate the total Fare paid across all passengers in the Titanic dataset.

In [25]:
total_fare = titanic['fare'].sum()
total_fare

np.float64(28693.9493)

2. Subset for passengers in first class (Pclass is 1) and calculate their total fare.

In [26]:
fare_class_1 = titanic[titanic['pclass'] == 1]['fare'].sum()
fare_class_1

np.float64(18177.4125)

3. Do the same for second class (Pclass is 2) and third class (Pclass is 3).

In [27]:
fare_class_2 = titanic[titanic['pclass'] == 2]['fare'].sum()
fare_class_2

np.float64(3801.8417)

In [28]:
fare_class_3 = titanic[titanic['pclass'] == 3]['fare'].sum()
fare_class_3

np.float64(6714.6951)

4. Combine the fare totals from first, second, and third classes into a list.

In [29]:
fare_list = [fare_class_1, fare_class_2, fare_class_3]
fare_list

[np.float64(18177.4125), np.float64(3801.8417), np.float64(6714.6951)]

5. Divide the totals for each class by the overall total fare to get the proportion of fare revenue by class.

In [30]:
proportion_by_class = [fare / total_fare for fare in fare_list]
proportion_by_class

[np.float64(0.6334928771899656),
 np.float64(0.1324962855496507),
 np.float64(0.23401083726038366)]

What percent of the total number of passengers on the Titanic belonged to each age group
(e.g., child, adult, senior)?
To answer the question perform following operation:
1. Create a new column, age group, that categorizes passengers into "child" (age < 18), "adult" (age
18{64), and "senior" (age 65 and above).

In [31]:
# Fill missing Age values
median_age = titanic['age'].median()
titanic['age'] = titanic['age'].fillna(median_age)

titanic['age_group'] = pd.cut(
    titanic['age'],
    bins=[0, 18, 64, 150],
    labels=['child', 'adult', 'senior'],
    right=False   # makes 18 included in adult
)

titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare_per_year,fare_per_class,age_group
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.329545,2.416667,adult
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1.875876,71.283300,adult
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.304808,2.641667,adult
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1.517143,53.100000,adult
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.230000,2.683333,adult

2. Calculate the total number of passengers on the Titanic.

In [32]:
total_passengers = len(titanic)
total_passengers

891

3. Count the number of passengers in each age group.

In [33]:
age_group_counts = titanic['age_group'].value_counts()
age_group_counts

age_group
adult     765
child     113
senior     13
Name: count, dtype: int64

4. Divide the count of each age group by the total number of passengers to get the proportion of passengers
in each age group.

In [34]:
age_group_proportion = age_group_counts / total_passengers
age_group_proportion

age_group
adult     0.858586
child     0.126824
senior    0.014590
Name: count, dtype: float64

5. Display the proportion as a percentage.

In [35]:
age_group_percentage = age_group_proportion * 100
age_group_percentage

age_group
adult     85.858586
child     12.682379
senior     1.459035
Name: count, dtype: float64